direction: right
vars: {
    d2-config: {
        layout-engine: elk {
            spacing.nodeNode: 15
            layered.spacing.nodeNodeBetweenLayers: 25
            layered.edgeRouting: "ORTHOGONAL"
        }
    }
}
