...@themes/default

direction: right

user: {
    label: "User"
    shape: image
    icon: "./icons/user.svg"
}

iframe: {
    label: "iFrame"
    style: {
        fill: "#f0f0f0"
        opacity: 0.4
    }

    key: {
        label: "Private Key"
        shape: image
        icon: "./icons/key.png"
    }


    keySss: {
        label: "SSS"
        shape: diamond
    }

    shares: {
        style.opacity: 0
        share1: {
            label: "Private Share 1\n(Device)"
            shape: image
            icon: "./icons/key_share_1.png"
        }

        share2: {
            label: "Private Share 2\n(Hot)"
            shape: image
            icon: "./icons/key_share_2.png"
        }

        share3: {
            label: "Private Share 3\n(Cold)"
            shape: image
            icon: "./icons/key_share_3.png"
        }
    }
    coldEncrypt: {
        label: "Encrypt"
        shape: diamond
    }
}

local: {
    label: "Cache\n(Browser Storage)"
    shape: image
    icon: "./icons/db.svg"
}

cold: {
    label: "Cold Storage"
    shape: image
    icon: "./icons/db.svg"
}

hot: {
    label: "Hot Storage"
    shape: image
    icon: "./icons/db.svg"
}


password: {
    label: "Password"
    shape: image
    icon: "./icons/password.svg"
}

user -> iframe.key {
    label: "owns"
}

user -> password {
    label: "knows"
}

iframe.key -> iframe.keySss {
}

iframe.keySss -> iframe.shares.share2 {
}

iframe.keySss -> iframe.shares.share3 {
}

iframe.shares.share1 -- local {
    label: "store"
}

iframe.shares.share2 -- hot {
    label: "store"
    style.animated: true
}

password -> iframe.coldEncrypt {
    label: "as entropy"
}

iframe.shares.share3 -- iframe.coldEncrypt {
    label: "as data"
}

iframe.coldEncrypt -- cold {
    label: "store"
    style.animated: true
}



